### ISSUE TITLE
Websocket reconnect issue with multiple clients: getting ghost clients 

### ISSUE THREAD

**Issue by mullerch** [nats-io/nats.ws#61] opened 2020-12-17 16:08 UTC
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

nats-server version 2.2.0-beta.34
synadia/nats-server:nightly-20201204

#### OS/Container environment:

Linux / Docker container

#### Steps or code to reproduce the issue:

Create two basic nats.ws client with the following connection options:
```
{ 
      name: 'client-',
      servers: 'ws://localhost:9222',
      token: '3secret',
      timeout: 2000,
      noEcho: true,
      maxReconnectAttempts: 10,
      pingInterval: 3000,
      maxPingOut: 2,
}
```

Create a nats server with the following Docker image: synadia/nats-server:nightly-20201204 and the following config:
```
listen: 127.0.0.1:4222
debug:   false
trace:   true

authorization: {
    token: "3secret"
}

websocket: {
    listen: 0.0.0.0:9222
    no_tls: true
}
```

1.  Start the server
2. Connect client 1
3. Connect client 2
4. Wait 5s
5. Kill the server
6. Wait 5s
7. Start the server

This will help reproduction: [issue-1778.zip](https://github.com/nats-io/nats-server/files/5710706/issue-1778.zip)

#### Expected result:

The server starts, both client try to reconnect. The server shows two "client connection created"  and two "CONNECT" messages which authenticates fine. The clients get a "reconnect" status message.

```
[1] 2020/12/17 16:03:02.342424 [INF] Starting nats-server version 2.2.0-beta.34
[1] 2020/12/17 16:03:02.342526 [DBG] Go build version go1.14.12
[1] 2020/12/17 16:03:02.342532 [INF] Git commit [8e095759]
[1] 2020/12/17 16:03:02.342563 [INF] Using configuration file: /nats/server.conf
[1] 2020/12/17 16:03:02.342615 [DBG] Created system account: "$SYS"
[1] 2020/12/17 16:03:02.343162 [INF] Listening for websocket clients on ws://0.0.0.0:9222
[1] 2020/12/17 16:03:02.343199 [WRN] Websocket not configured with TLS. DO NOT USE IN PRODUCTION!
[1] 2020/12/17 16:03:02.343208 [DBG] Get non local IPs for "0.0.0.0"
[1] 2020/12/17 16:03:02.343425 [DBG]   ip=172.17.0.2
[1] 2020/12/17 16:03:02.343543 [INF] Listening for client connections on 127.0.0.1:4222
[1] 2020/12/17 16:03:02.343579 [INF] Server id is NAZRKRPGYC56ZINY76B4R6OTGSKMI2VZB5KO4AVCYDD7AGSNH54QJAIF
[1] 2020/12/17 16:03:02.343584 [INF] Server name is NAZRKRPGYC56ZINY76B4R6OTGSKMI2VZB5KO4AVCYDD7AGSNH54QJAIF
[1] 2020/12/17 16:03:02.343588 [INF] Server is ready
[1] 2020/12/17 16:03:02.637848 [DBG] 172.17.0.1:45256 - wid:2 - Client connection created
[1] 2020/12/17 16:03:02.642905 [TRC] 172.17.0.1:45256 - wid:2 - <<- [CONNECT {"protocol":1,"version":"1.0.0-114","lang":"nats.ws","echo":false,"verbose":false,"pedantic":false,"name":"client-","auth_token":"3secret"}]
[1] 2020/12/17 16:03:02.643120 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:02.643167 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:02.648342 [DBG] 172.17.0.1:45260 - wid:3 - Client connection created
[1] 2020/12/17 16:03:02.654492 [TRC] 172.17.0.1:45260 - wid:3 - <<- [CONNECT {"protocol":1,"version":"1.0.0-114","lang":"nats.ws","echo":false,"verbose":false,"pedantic":false,"name":"client-","auth_token":"3secret"}]
[1] 2020/12/17 16:03:02.654558 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:02.654564 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:04.752051 [DBG] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - Client Ping Timer
[1] 2020/12/17 16:03:04.752120 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - ->> [PING]
[1] 2020/12/17 16:03:04.756260 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - <<- [PONG]
[1] 2020/12/17 16:03:04.896866 [DBG] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - Client Ping Timer
[1] 2020/12/17 16:03:04.896939 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - ->> [PING]
[1] 2020/12/17 16:03:04.902107 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - <<- [PONG]
[1] 2020/12/17 16:03:05.666494 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:05.666565 [TRC] 172.17.0.1:45256 - wid:2 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:06.516147 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:06.516183 [TRC] 172.17.0.1:45260 - wid:3 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
```

#### Actual result:

Sometime, the expected result occurs, sometimes, we can see 4 "Client connection created" messages with 4 different wid. Only two CONNECT messages are received. The two connections that don't have a CONNECT message get an Authentication Timeout message (result of auth enabled). The clients get a "NATS connection closed 'Authentication Timeout'" failure.

```
[1] 2020/12/17 16:03:13.638188 [INF] Starting nats-server version 2.2.0-beta.34
[1] 2020/12/17 16:03:13.638290 [DBG] Go build version go1.14.12
[1] 2020/12/17 16:03:13.638296 [INF] Git commit [8e095759]
[1] 2020/12/17 16:03:13.638301 [INF] Using configuration file: /nats/server.conf
[1] 2020/12/17 16:03:13.638331 [DBG] Created system account: "$SYS"
[1] 2020/12/17 16:03:13.638993 [INF] Listening for websocket clients on ws://0.0.0.0:9222
[1] 2020/12/17 16:03:13.639030 [WRN] Websocket not configured with TLS. DO NOT USE IN PRODUCTION!
[1] 2020/12/17 16:03:13.639039 [DBG] Get non local IPs for "0.0.0.0"
[1] 2020/12/17 16:03:13.639426 [DBG]   ip=172.17.0.2
[1] 2020/12/17 16:03:13.639545 [INF] Listening for client connections on 127.0.0.1:4222
[1] 2020/12/17 16:03:13.639577 [INF] Server id is NAOYR6QS2GMEQG4TFZF7D3SNFWEL536KSW57ZJUTSPEMZ5UGFF6UBXHM
[1] 2020/12/17 16:03:13.639582 [INF] Server name is NAOYR6QS2GMEQG4TFZF7D3SNFWEL536KSW57ZJUTSPEMZ5UGFF6UBXHM
[1] 2020/12/17 16:03:13.639586 [INF] Server is ready
[1] 2020/12/17 16:03:13.931292 [DBG] 172.17.0.1:45276 - wid:2 - Client connection created
[1] 2020/12/17 16:03:13.948180 [DBG] 172.17.0.1:45280 - wid:3 - Client connection created
[1] 2020/12/17 16:03:13.960071 [DBG] 172.17.0.1:45284 - wid:4 - Client connection created
[1] 2020/12/17 16:03:13.988728 [DBG] 172.17.0.1:45288 - wid:5 - Client connection created
[1] 2020/12/17 16:03:13.993530 [TRC] 172.17.0.1:45288 - wid:5 - <<- [CONNECT {"protocol":1,"version":"1.0.0-114","lang":"nats.ws","echo":false,"verbose":false,"pedantic":false,"name":"client-","auth_token":"3secret"}]
[1] 2020/12/17 16:03:13.993665 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:13.993701 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:15.932328 [TRC] 172.17.0.1:45276 - wid:2 - ->> [-ERR Authentication Timeout]
[1] 2020/12/17 16:03:15.932381 [DBG] 172.17.0.1:45276 - wid:2 - Authentication Timeout
[1] 2020/12/17 16:03:15.932411 [DBG] 172.17.0.1:45276 - wid:2 - Client connection closed: Authentication Timeout
[1] 2020/12/17 16:03:15.948879 [TRC] 172.17.0.1:45280 - wid:3 - ->> [-ERR Authentication Timeout]
[1] 2020/12/17 16:03:15.948917 [DBG] 172.17.0.1:45280 - wid:3 - Authentication Timeout
[1] 2020/12/17 16:03:15.948946 [DBG] 172.17.0.1:45280 - wid:3 - Client connection closed: Authentication Timeout
[1] 2020/12/17 16:03:15.960466 [TRC] 172.17.0.1:45284 - wid:4 - ->> [-ERR Authentication Timeout]
[1] 2020/12/17 16:03:15.960566 [DBG] 172.17.0.1:45284 - wid:4 - Authentication Timeout
[1] 2020/12/17 16:03:15.960575 [DBG] 172.17.0.1:45284 - wid:4 - Client connection closed: Authentication Timeout
[1] 2020/12/17 16:03:15.971841 [DBG] 172.17.0.1:45294 - wid:6 - Client connection created
[1] 2020/12/17 16:03:15.976952 [TRC] 172.17.0.1:45294 - wid:6 - <<- [CONNECT {"protocol":1,"version":"1.0.0-114","lang":"nats.ws","echo":false,"verbose":false,"pedantic":false,"name":"client-","auth_token":"3secret"}]
[1] 2020/12/17 16:03:15.995103 [DBG] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - Client Ping Timer
[1] 2020/12/17 16:03:15.995162 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - ->> [PING]
[1] 2020/12/17 16:03:15.998132 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - <<- [PONG]
[1] 2020/12/17 16:03:16.021763 [TRC] 172.17.0.1:45294 - wid:6 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:16.021813 [TRC] 172.17.0.1:45294 - wid:6 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:17.017397 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - <<- [PING]
[1] 2020/12/17 16:03:17.017435 [TRC] 172.17.0.1:45288 - wid:5 - "v1.0.0-114:nats.ws:client-" - ->> [PONG]
[1] 2020/12/17 16:03:18.234340 [DBG] 172.17.0.1:45294 - wid:6 - "v1.0.0-114:nats.ws:client-" - Client Ping Timer
[1] 2020/12/17 16:03:18.234407 [TRC] 172.17.0.1:45294 - wid:6 - "v1.0.0-114:nats.ws:client-" - ->> [PING]
[1] 2020/12/17 16:03:18.236898 [TRC] 172.17.0.1:45294 - wid:6 - "v1.0.0-114:nats.ws:client-" - <<- [PONG]
```

If the problem doesn't occur the first time, you can just go on with step 5-7. I usually have the problem after 2-3 tries. It may be related to the timing.

**Comment by kozlovic** [comment] 2020-12-17 16:28
@mullerch @aricart I have transferred the issue from nats-server repo to nats-ws. I strongly believe that this is a client behavior, not the server (that is, the server cannot create WS connections out of thin air, so those 4 connections are created by the client). Since you have a ping interval of 3s and a maxPingOut of 2, it is getting close to the time you wait for the server restart, so it could be that the client has some issue with those connections that are supposed to be marked as closed?

**Comment by mullerch** [comment] 2020-12-17 16:34
@kozlovic Actually I was not able to reproduce the bug using only a single client. That's why I supposed it was server related.

I've tried to raise the maxPingOut to 5 and I can still reproduce it.

**Comment by aricart** [comment] 2020-12-17 17:27
@mullerch thank you for including the setup

If I run your example - I copied the issue dir to examples/ on a clone of this repo, and then
`npm run start-http` to start a server
and `nats-server -c /examples/issuexxx/server.conf`

If I stop the server, only two clients connect as I would expect.

```
nats-server -c examples/issue-1778/server.conf
[15039] 2020/12/17 11:23:54.749020 [INF] Starting nats-server version 2.2.0-beta.35
[15039] 2020/12/17 11:23:54.749112 [DBG] Go build version go1.14.10
[15039] 2020/12/17 11:23:54.749114 [INF] Git commit [not set]
[15039] 2020/12/17 11:23:54.749117 [INF] Using configuration file: examples/issue-1778/server.conf
[15039] 2020/12/17 11:23:54.749128 [DBG] Created system account: "$SYS"
[15039] 2020/12/17 11:23:54.749519 [INF] Listening for websocket clients on ws://0.0.0.0:9222
[15039] 2020/12/17 11:23:54.749525 [WRN] Websocket not configured with TLS. DO NOT USE IN PRODUCTION!
[15039] 2020/12/17 11:23:54.749528 [INF] Listening for websocket clients on ws://0.0.0.0:9222
[15039] 2020/12/17 11:23:54.749532 [DBG] Get non local IPs for "0.0.0.0"
[15039] 2020/12/17 11:23:54.749672 [DBG]   ip=192.168.86.31
[15039] 2020/12/17 11:23:54.749759 [INF] Listening for client connections on 127.0.0.1:4222
[15039] 2020/12/17 11:23:54.749763 [INF] Server id is NBIIIWZ5NUT4I7ASMFW66RHBDKTWSTLIZDPBT7PNFYIDGSMODZVRGZ5J
[15039] 2020/12/17 11:23:54.749765 [INF] Server name is NBIIIWZ5NUT4I7ASMFW66RHBDKTWSTLIZDPBT7PNFYIDGSMODZVRGZ5J
[15039] 2020/12/17 11:23:54.749767 [INF] Server is ready
[15039] 2020/12/17 11:23:56.405030 [DBG] [::1]:51433 - wid:2 - Client connection created
[15039] 2020/12/17 11:23:56.406170 [TRC] [::1]:51433 - wid:2 - <<- [CONNECT {"protocol":1,"version":"1.0.0-114","lang":"nats.ws","echo":false,"verbose":false,"pedantic":false,"name":"client-b","auth_token":"3secret"}]
[15039] 2020/12/17 11:23:56.406269 [TRC] [::1]:51433 - wid:2 - "v1.0.0-114:nats.ws:client-b" - <<- [PING]
[15039] 2020/12/17 11:23:56.406273 [TRC] [::1]:51433 - wid:2 - "v1.0.0-114:nats.ws:client-b" - ->> [PONG]
[15039] 2020/12/17 11:23:56.885701 [DBG] [::1]:51435 - wid:3 - Client connection created
[15039] 2020/12/17 11:23:56.886683 [TRC] [::1]:51435 - wid:3 - <<- [CONNECT {"protocol":1,"version":"1.0.0-114","lang":"nats.ws","echo":false,"verbose":false,"pedantic":false,"name":"client-a","auth_token":"3secret"}]
[15039] 2020/12/17 11:23:56.886714 [TRC] [::1]:51435 - wid:3 - "v1.0.0-114:nats.ws:client-a" - <<- [PING]
[15039] 2020/12/17 11:23:56.886718 [TRC] [::1]:51435 - wid:3 - "v1.0.0-114:nats.ws:client-a" - ->> [PONG]
[15039] 2020/12/17 11:23:58.773487 [DBG] [::1]:51433 - wid:2 - "v1.0.0-114:nats.ws:client-b" - Client Ping Timer
[15039] 2020/12/17 11:23:58.773562 [TRC] [::1]:51433 - wid:2 - "v1.0.0-114:nats.ws:client-b" - ->> [PING]
[15039] 2020/12/17 11:23:58.773968 [TRC] [::1]:51433 - wid:2 - "v1.0.0-114:nats.ws:client-b" - <<- [PONG]
[15039] 2020/12/17 11:23:59.026949 [DBG] [::1]:51435 - wid:3 - "v1.0.0-114:nats.ws:client-a" - Client Ping Timer
[15039] 2020/12/17 11:23:59.026983 [TRC] [::1]:51435 - wid:3 - "v1.0.0-114:nats.ws:client-a" - ->> [PING]
[15039] 2020/12/17 11:23:59.027359 [TRC] [::1]:51435 - wid:3 - "v1.0.0-114:nats.ws:client-a" - <<- [PONG]
[15039] 2020/12/17 11:23:59.411502 [TRC] [::1]:51433 - wid:2 - "v1.0.0-114:nats.ws:client-b" - <<- [PING]
[15039] 2020/12/17 11:23:59.411514 [TRC] [::1]:51433 - wid:2 - "v1.0.0-114:nats.ws:client-b" - ->> [PONG]
[15039] 2020/12/17 11:24:00.882835 [TRC] [::1]:51435 - wid:3 - "v1.0.0-114:nats.ws:client-a" - <<- [PING]
[15039] 2020/12/17 11:24:00.882848 [TRC] [::1]:51435 - wid:3 - "v1.0.0-114:nats.ws:client-a" - ->> [PONG]
[15039] 2020/12/17 11:24:02.416586 [TRC] [::1]:51433 - wid:2 - "v1.0.0-114:nats.ws:client-b" - <<- [PING]
```

 is it possible you have some browser tabs that you are not looking at?

**Comment by aricart** [comment] 2020-12-17 17:28
@mullerch also what browser are you using?

**Comment by aricart** [comment] 2020-12-17 17:38
Just to make sure also ran with docker:
`docker run -v /Users/synadia/Dropbox/code/src/github.com/nats-io/nats.ws/examples/issue-1778:/conf -p 9222:9222 synadia/nats-server:nightly-20201204 -c /conf/server.conf` and same results

**Comment by mullerch** [comment] 2020-12-17 17:58
-- is it possible you have some browser tabs that you are not looking at?

I don't think so. Even if it's the case it would not result in this behavior.

-- also what browser are you using?

I had the problem in both Chrome 87.0.4280.88, Firefox 83.0 (64-bit) and Edge 87.0.664.60 (the chromium based). The browser is running Windows 10.

I could also reproduce it using a node server (http-server).

How many times have you tried restarting the server? It does not occur every time.

**Comment by kozlovic** [comment] 2020-12-17 18:00
I did try probably a 100 times now with both the server build from main branch and the docker image. To kill the server, I tried ctrl+c, ctrl+\ (cause a dump stack) or from docker doing `docker kill <container id>`. In all cases, clients reconnect fine (Brave and Chrome), although Safari will quickly detect the connection as stale if I don't restart the server fast enough.

The clients are running on macOS..

**Comment by mullerch** [comment] 2020-12-17 18:04
This problems occurs both in my project and in this reproduction setup. In my project the server is running on an embedded linux device and the browser on a Windows computer. On the target the server is embedded in my go application and killed with ctrl-c. With docker I run it with -it and kill with ctrl-c.

I can give a try tomorrow on an ubuntu machine.

**Comment by aricart** [comment] 2020-12-17 18:50
Can you instrument your connection time - when you call connect until the time that the connection resolves?

**Comment by mullerch** [comment] 2020-12-18 10:18
So I tried on another computer running Linux. I works fine with Chromium, server running locally. Using the same server and accessing from remote Windows computer with Chrome it fails.

Here is both data so you can compare:
[windows-chrome-nok.zip](https://github.com/nats-io/nats.ws/files/5715072/windows-chrome-nok.zip)

**Comment by mullerch** [comment] 2020-12-21 09:24
Is that enough to investigate or do you need more data?

**Comment by aricart** [comment] 2020-12-21 14:05
Will look. Thanks

**Comment by aricart** [comment] 2020-12-21 17:44
@mullerch so testing on windows on my side didn't yield any different behavior. The clients reconnect unless I wait too long and the maxReconnectAttempt triggers - setting that to -1, keeps them trying forever. 

The only thing that I am worried about is whether for some reason running on the nuk is causing the timeout to fire, thus closing the connection. On a Windows desktop this doesn't happen but given the smaller device not sure what it is doing.

If you would be so kind modify your nats.mjs:

```
               async dial(srv) {
                    const pong = this.prepare();
                    const timer = util_ts_7.timeout(this.options.timeout || 20000);
                    try {
                        await this.transport.connect(srv, this.options);
                        (async () => {
                            try {
                                for await (const b of this.transport) {
                                    this.parser.parse(b);
                                }
                            }
                            catch (err) {
                                console.log("reader closed", err);
                            }
                        })().then();
                    }
                    catch (err) {
                       // add the following line:
                       timer.cancel();
                        pong.reject(err);
                    }
```

**Comment by aricart** [comment] 2020-12-21 17:45
The above should prevent the timer kicking at the time the correction is rejected by the websocket transport error.

**Comment by mullerch** [comment] 2020-12-22 08:05
It doesn't help. Actually this catch is processed on the client disconnection. When the error occurs, it's not.

As we can see in the log, the problem occurs on a send, as the socket is reconnecting:
```
Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at WsTransport.send (http://localhost:8001/nats.mjs:8226:37)
    at ProtocolHandler.processInfo (http://localhost:8001/nats.mjs:6991:44)
    at ProtocolHandler.push (http://localhost:8001/nats.mjs:7027:34)
    at Parser.parse (http://localhost:8001/nats.mjs:6375:57)
    at http://localhost:8001/nats.mjs:6854:49
```

After some investigation, I noticed that the `await this.transport.connect(srv, this.options);` sometimes returns successfully despite a TIMEOUT occurring (that is logged as uncaught). After that the async for parse loop is started and fails on the next message enqueued.

I've added some trace logs:
```
async dial(srv) {
                    const id = Math.round(Math.random() * 1000000);
                    const pong = this.prepare();
                    const timer = util_ts_7.timeout(this.options.timeout || 20000);
                    try {
                        console.log('CONNECT', id);
                        await this.transport.connect(srv, this.options);
                        console.log('CONNECTED', id);
                        (async () => {
                            try {
                                for await (const b of this.transport) {
                                    console.log('PARSE', id);
                                    this.parser.parse(b);
                                }
                            }
                            catch (err) {
                                console.log("reader closed", err, id);
                            }
                        })().then();
                    }
                    catch (err) {
                        // add the following line:
                        console.log('ISUES-61');
                        timer.cancel();
                        pong.reject(err);
                    }
```

That lead to:
```
NatsConnectionImpl {draining: false, listeners: Array(0), options: {…}, protocol: ProtocolHandler}
4nats.mjs:6857 PARSE 493685
nats.mjs:6851 CONNECT 618722
nats.mjs:8136 WebSocket connection to 'ws://127.0.0.1:9222/' failed: Connection closed before receiving a handshake response
connect @ nats.mjs:8136
dial @ nats.mjs:6852
dialLoop @ nats.mjs:6906
disconnected @ nats.mjs:6831
(anonymous) @ nats.mjs:6815
nats.mjs:6868 ISUES-61
nats.mjs:6851 CONNECT 129962
nats.mjs:158 Uncaught (in promise) NatsError: TIMEOUT
    at Function.errorForCode (http://localhost:8001/nats.mjs:166:28)
    at http://localhost:8001/nats.mjs:4756:45
NatsError @ nats.mjs:158
errorForCode @ nats.mjs:166
(anonymous) @ nats.mjs:4756
setTimeout (async)
(anonymous) @ nats.mjs:4755
timeout @ nats.mjs:4748
dial @ nats.mjs:6849
dialLoop @ nats.mjs:6906
async function (async)
dialLoop @ nats.mjs:6906
disconnected @ nats.mjs:6831
(anonymous) @ nats.mjs:6815
Promise.then (async)
prepare @ nats.mjs:6812
dial @ nats.mjs:6848
dialLoop @ nats.mjs:6906
connect @ nats.mjs:6932
(anonymous) @ nats.mjs:7375
connect @ nats.mjs:7373
connect @ nats.mjs:8294
doConnect @ client.js:33
(anonymous) @ client.js:83
nats.mjs:6853 CONNECTED 129962 // Problem: if a timeout occurs, connect() should throw an error
nats.mjs:6851 CONNECT 94589
nats.mjs:6857 PARSE 129962 // Problem: trying to send on closed socket
nats.mjs:8230 Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at WsTransport.send (http://localhost:8001/nats.mjs:8230:37)
    at ProtocolHandler.processInfo (http://localhost:8001/nats.mjs:6995:44)
    at ProtocolHandler.push (http://localhost:8001/nats.mjs:7031:34)
    at Parser.parse (http://localhost:8001/nats.mjs:6375:57)
    at http://localhost:8001/nats.mjs:6858:49
send @ nats.mjs:8230
processInfo @ nats.mjs:6995
push @ nats.mjs:7031
parse @ nats.mjs:6375
(anonymous) @ nats.mjs:6858
async function (async)
(anonymous) @ nats.mjs:6856
dial @ nats.mjs:6864
async function (async)
dial @ nats.mjs:6852
dialLoop @ nats.mjs:6906
async function (async)
dialLoop @ nats.mjs:6906
disconnected @ nats.mjs:6831
(anonymous) @ nats.mjs:6815
Promise.then (async)
prepare @ nats.mjs:6812
dial @ nats.mjs:6848
dialLoop @ nats.mjs:6906
connect @ nats.mjs:6932
(anonymous) @ nats.mjs:7375
connect @ nats.mjs:7373
connect @ nats.mjs:8294
doConnect @ client.js:33
(anonymous) @ client.js:83
nats.mjs:8230 Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at WsTransport.send (http://localhost:8001/nats.mjs:8230:37)
    at ProtocolHandler.processInfo (http://localhost:8001/nats.mjs:6996:44)
    at ProtocolHandler.push (http://localhost:8001/nats.mjs:7031:34)
    at Parser.parse (http://localhost:8001/nats.mjs:6375:57)
    at http://localhost:8001/nats.mjs:6858:49
send @ nats.mjs:8230
processInfo @ nats.mjs:6996
push @ nats.mjs:7031
parse @ nats.mjs:6375
(anonymous) @ nats.mjs:6858
async function (async)
(anonymous) @ nats.mjs:6856
dial @ nats.mjs:6864
async function (async)
dial @ nats.mjs:6852
dialLoop @ nats.mjs:6906
async function (async)
dialLoop @ nats.mjs:6906
disconnected @ nats.mjs:6831
(anonymous) @ nats.mjs:6815
Promise.then (async)
prepare @ nats.mjs:6812
dial @ nats.mjs:6848
dialLoop @ nats.mjs:6906
connect @ nats.mjs:6932
(anonymous) @ nats.mjs:7375
connect @ nats.mjs:7373
connect @ nats.mjs:8294
doConnect @ client.js:33
(anonymous) @ client.js:83
nats.mjs:6853 CONNECTED 94589
nats.mjs:6857 PARSE 94589
nats.mjs:6851 CONNECT 182277
nats.mjs:6857 PARSE 94589
nats.mjs:158 Uncaught (in promise) NatsError: 'Authentication Timeout'
    at Function.toError (http://localhost:8001/nats.mjs:6944:32)
    at ProtocolHandler.processError (http://localhost:8001/nats.mjs:6967:49)
    at ProtocolHandler.push (http://localhost:8001/nats.mjs:7022:34)
    at Parser.parse (http://localhost:8001/nats.mjs:6228:57)
    at http://localhost:8001/nats.mjs:6858:49
nats.mjs:6853 CONNECTED 182277
nats.mjs:6857 PARSE 182277
```

**Comment by aricart** [comment] 2020-12-22 20:00
@mullerch I am wondering if for some reason the server is failing to answer quickly enough.
Can you add the connection option `debug: true` so that we can see what data the client and the server are exchanging.

Also - I am interested in seeing if the timeout is killing the connection because the server is not returning data quickly enough, or the data is partial or what - the server will have a deadline of around 2 seconds if it doesn't see data from the client it will cut it off. Likewise the client has a timeout (by default it is set high - like 20000ms) where if the protocol exchange between the client and the server doesn't happen the timer will trigger.

**Comment by mullerch** [comment] 2020-12-23 09:42
I've made some additional tests, with `debug: true`. I think I have a 100% reproduction scenario:

Scenario A:
1. Start nats server
  `docker run --rm -it -p 9222:9222 -v C:\path\to\cfg\:/nats synadia/nats-server:nightly-20201221 -c /nats/server.conf`
2. Start client 1 (cfg attached)
3. Start client 2 (same cfg)
4. Wait 3s
5. Kill the server (ctrl-c)
6. Wait for both client being disconnected, trying to reconnect and having a timeout (~2-3s)
7. Start the server

**Expected result:**

- The clients timeout (server down) and show the timeout error, connection is not successful
- The servers creates two client connections (wid)
- The clients send a CONNECT message
- The clients are connected

**Actual result:**

Server side:
- The server create 4 client connections
- Two of them will receive a CONNECT message
- Two of them will have an authentication timeout after 2 sec and the client connection is closed

Client side:
- The clients timeout (server down) and show the timeout error, connection is not successful
- Until the server is restarted, the connection retries are timing out correctly and the connect() is detected as having failed.
- As soon as the server is started, one of the client will get a timeout but will still go on as connect() would have succeeded.
- This client will then get an authentication timeout and will try to reconnect. It will succeed but the connection actually bound to the unsuccessful connection, it will therefore not be usable by the client application.
- The other client will connect successfully. Event if it receives an authentication timeout, it will detect it correctly (the connection will close) and try to reconnect. It will succeed and use the new connection and be usable.

Others
- It am not able to reproduce the problem with a single client
- When using three clients, generally (>80%) two of them have the bug, the last not. Sometime (other 20%) only one has the bug. It never happens that none has the bug.
- The bug only occurs with a connection timeout <= 2000
- The bug occurrence differs when changing the reconnectTimeWait. e.g. with 1000 the problem may occur on both client. With 5000 I could not reproduce the bug.

Attached you have the log of two client with `debug: true` in the reproduction scenario A.

- [client-config.txt](https://github.com/nats-io/nats.ws/files/5734421/client-config.txt)
- [client-1-ok.log](https://github.com/nats-io/nats.ws/files/5734423/client-1-ok.log)
- [client-2-error.log](https://github.com/nats-io/nats.ws/files/5734420/client-2-error.log)
- [server.log](https://github.com/nats-io/nats.ws/files/5734422/server.log)

Finally, I think that you should focus on reproduction as this problem seems quite complex and our current process is quite inefficient.

**Comment by aricart** [comment] 2020-12-23 16:33
I did notice that the websocket client is not trying to parse a protocol line before resolving the connection - it simply trusts the websocket notification - thanks for the info - let me see if I can make some progress on this for you. My question is still why doesn't it only happen on the nuk - on a regular desktop (windows or otherwise) doesn't happen, but yes I believe you there's an issue

**Comment by aricart** [comment] 2021-01-08 17:43
@mullerch Thank you very much for your detailed last test case - I was able to reproduce the issue. I will publish the fix as soon as it is merged into master.

**Closed** 2021-01-08 19:51 UTC

**Comment by aricart** [comment] 2021-01-08 20:42
npm install nats.ws@latest to get the new changes
