### ISSUE TITLE
Module parse failed: Unexpected token (289:46)

### ISSUE THREAD

**Issue by sharif2008** [nats-io/nats.ws#142] opened 2022-03-13 21:01 UTC
Hi, I am facing this issue  when I tried to run it 

where-

```
/app/node_modules/nats.ws/esm/nats.js 289:46
Module parse failed: Unexpected token (289:46)
File was processed with these loaders:
 * ../../node_modules/babel-loader/lib/index.js
 * ../../node_modules/babel-loader/lib/index.js
 * 
You may need an additional loader to handle the result of these loaders. 
function isHeartbeatMsg(msg) {
>   return isFlowControlMsg(msg) && msg.headers?.description === "Idle Heartbeat";
}
```

Where 

 "nats.ws": "next"
  "@babel/preset-env": "7.16.8",
 "babel-plugin-transform-class-properties": "^6.24.1",
  "@babel/plugin-proposal-class-properties": "^7.16.7"

**Comment by aricart** [comment] 2022-03-14 15:28
Using React or what - the npm bundle should do the right thing if you just import "nats.ws". All these are valid, and get resolved in current React.

**Comment by aricart** [comment] 2022-03-14 15:34
I suspect the issue is your babel is not a current version and it doesn't like the `obj?.field` syntax, you'll probably need something like https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining

**Comment by aricart** [comment] 2022-03-14 18:03
you need to move to the current version of react if you want a seamless experience. The old versions of react are not supported.

**Closed** 2022-03-14 18:04 UTC
