### ISSUE TITLE
Compiling Angular code with nats.ws as dependency fails

### ISSUE THREAD

**Issue by cuddlecake** [nats-io/nats.ws#68] opened 2021-01-13 11:18 UTC
Hi there,

first of all, thank you for your work. This repo helped us a lot.

Currently, we are using an older version of nats.ws, and when trying to update to nats.ws 1.0.0-117, we encounter a few compilation errors, such as:

```
Error: ./node_modules/nats.ws/nats.mjs 1070:22
Module parse failed: Unexpected token (1070:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         this._off = 0;
|     }
>     _tryGrowByReslice = (n)=>{
|         const l = this._buf.byteLength;
|         if (n <= this.capacity - l) {
 @ ./src/app/app.component.ts 2:0-34 40:8-15
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

This is a log from trying to compile [this example repo](https://github.com/cuddlecake/nats-ws-angular-compile-error-example) I set up, but it's the same log in our main application.

The example repo uses Angular 11, we currently use Angular 10.

If I follow the errors and fix them, the code works, but this is not a good solution because we would need to copy the code from the dependency into our own repository and keep making the same modifications for all upcoming updates.

**Comment by emcpadden** [comment] 2021-01-25 15:56
@cuddlecake what was the fix you needed to make?  I'm running into the same problem

**Comment by aricart** [comment] 2021-01-25 17:10
Better yet - can you open a PR with your changes - thanks

**Comment by cuddlecake** [comment] 2021-01-27 09:28
It seems that the main problem is this feature: https://github.com/tc39/proposal-class-fields.

I have made PRs to remove the few occurences of this that the source code includes. I expect that this also removes the occurences in the output code.

It could probably be fixed cleanly if the build output does not include class field initializers even if the source code does, but I don't know how to do that, with `deno` being completely foreign to me.

**Comment by aricart** [comment] 2021-01-29 15:11
I did an initial pass at many of those conditions as depending on the version of Deno used to generate the code, some of these constructs telegraph back - safari will absolutely fail at those. Seems the transpilation by other tools is more sensitive. Thanks for the contributions.

**Comment by aricart** [comment] 2021-01-29 15:48
Going to assume that the above PRs are the last of the initializers, so I will close the issue. Please feel free to open another issue or PR if you see another missed condition. Thanks.

**Closed by aricart** 2021-01-29 15:48 UTC

**Comment by cuddlecake** [comment] 2021-02-01 13:30
Hi @aricart, could you perhaps release a new version of this lib?

**Comment by Nevermind-s** [comment] 2021-02-09 12:39
Hi @aricart would it possible to release a version for this fix?

**Comment by aricart** [comment] 2021-02-09 13:30
Yes rc one in a bit

**Comment by aricart** [comment] 2021-02-09 16:30
@Nevermind-s  @cuddlecake  I have pushed a new npm package, please open a new issue if something doesn't seem right.

**Comment by cuddlecake** [comment] 2021-02-09 17:30
It compiles now, but it's still awkward to consume.

To the Angular users:

If you are using Jest for testing, you will run into another [rabbit hole](https://github.com/facebook/jest/issues/9430) because of *.mjs.
For now, I solves this by adding a `nats.mock.ts` file somewhere, with the content:

```ts
// nats.mock.ts

export const connect = jest.fn();
```

with usage in a test suite:

```ts
// socket.service.spec.ts
// Note that, even if you don't use it in tests, any test that indirectly imports `nats.ws` will break.

describe('My Socket Service', () => {
    connectMock = <jest.Mock>nats.connect;
    beforeEach(() => {
        connectMock.mockReset();
    })
})
```

and the addition to jest.config.js:

```js
module.exports = {
    // ... other config
    transform: {
        // I think this should already be included if you are using jest for Angular
        '^.+\\.(ts|html)$': 'ts-jest',
    },
    moduleNameMapper: {
        // note that the file ending here is `.js`, not `.ts`, probably because of ts-jest
        'nats.ws': 'path/to/nats.mock.js',
    }
}
```

**Comment by mullerch** [comment] 2021-03-18 11:18
I have a similar issue with the latest versions (it was fine with 116).

`Unexpected token: punc (.)`

I'm using vuejs, with vue-cli 4.5.12 that ships with webpack 4.46.0. The issue is reported by [Terser](https://webpack.js.org/plugins/terser-webpack-plugin/) 4.8.0.

The errors refers to a temp file that is immediately deleted so I have no idea where it's exactly from.

**Comment by aricart** [comment] 2021-03-18 13:23
@mullerch @cuddlecake - I have been considering on my side to simply make all the tests run on Deno. The reason for this is that deno now supports the browser's websocket API, and can consume all of this directly. Alternatively, you can look at what I am currently doing for tests - I checkout the base client and then have tsc compile the base library and run tests that way.

For the unexpected token, I am wondering if your webpack is complaining about optional chaining (`one?.two`)

**Comment by mullerch** [comment] 2021-03-18 15:12
I noticed that because it is a mjs file, the wrong loader was used. Using babel-loader the optional-chaining is transpiled and everything builds with webpack 4.

**Comment by aricart** [comment] 2021-03-18 15:38
@mullerch glad it worked.

**Comment by aricart** [comment] 2021-03-27 21:10
For folks that are using this under react and angular, I have added cjs to a branch and published as nats.ws@next.
This will hopefully make it much easier to work when using other transpilers in the middle. The other benefit is that out of the box it becomes possible to do a very easy shim:


```javascript
// shim the websocket library
globalThis.WebSocket = require("websocket").w3cwebsocket;
const { connect } = require("nats.ws");

// write some code that runs on the server
```

Which will make the library run in node directly - I would imagine the performance of the nats.js (native tcp node library) will be better, but it may be useful in cases where some of the services are behind websocket proxies.

**Comment by aricart** [comment] 2021-03-27 21:14
In case you were not thinking of Deno, any esm code you write can also be imported and executed by Deno directly as deno has a built-in W3C Websocket.
